//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageList.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessageList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ブラウザへ情報を送信できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrowserRunError {
            get {
                return ResourceManager.GetString("BrowserRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListInboxRestore {
            get {
                return ResourceManager.GetString("MessageListInboxRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信者:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListMailAuthor {
            get {
                return ResourceManager.GetString("MessageListMailAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   迷惑メールのチェック中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamChecking {
            get {
                return ResourceManager.GetString("MessageListSpamChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamError {
            get {
                return ResourceManager.GetString("MessageListSpamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックが完了しました。メール数: {0} 通。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamReceive {
            get {
                return ResourceManager.GetString("MessageListSpamReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックが完了しました。 全 {0} 通中  {1} 通表示。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamReceiveOver {
            get {
                return ResourceManager.GetString("MessageListSpamReceiveOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信日時:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListToolTip {
            get {
                return ResourceManager.GetString("MessageListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListToolTipTime {
            get {
                return ResourceManager.GetString("MessageListToolTipTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＭＳ ゴシック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsMessageListDefaultFont {
            get {
                return ResourceManager.GetString("SettingsMessageListDefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GmailChecker 2 - 月光 - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月光 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoftwareNameShort {
            get {
                return ResourceManager.GetString("SoftwareNameShort", resourceCulture);
            }
        }
    }
}
