//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gekko.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gekko.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   メイリオ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutFont {
            get {
                return ResourceManager.GetString("AboutFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアカウントを使用しない(&amp;U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountListDisable {
            get {
                return ResourceManager.GetString("AccountListDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアカウントを使用する(&amp;U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountListEnable {
            get {
                return ResourceManager.GetString("AccountListEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   （なし） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountSettingAltAName {
            get {
                return ResourceManager.GetString("AccountSettingAltAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountSettingTestConnecting {
            get {
                return ResourceManager.GetString("AccountSettingTestConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続に成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountSettingTestSucceeded {
            get {
                return ResourceManager.GetString("AccountSettingTestSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント名が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountSettingVoidAccount {
            get {
                return ResourceManager.GetString("AccountSettingVoidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドメイン名が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountSettingVoidDomain {
            get {
                return ResourceManager.GetString("AccountSettingVoidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcoountSettingVoidPassword {
            get {
                return ResourceManager.GetString("AcoountSettingVoidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再開しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BalloonPowerResumed {
            get {
                return ResourceManager.GetString("BalloonPowerResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザへ情報を送信できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrowserRunError {
            get {
                return ResourceManager.GetString("BrowserRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ただの例外呼び出しテストです。もし、これがデバッグ以外で発生した場合は作者へご連絡ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionManagerApplicationExceptionHint {
            get {
                return ResourceManager.GetString("ExceptionManagerApplicationExceptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードに情報をコピーしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionManagerClipboard {
            get {
                return ResourceManager.GetString("ExceptionManagerClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタックトレースの例外説明をご参照ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionManagerDefaultHint {
            get {
                return ResourceManager.GetString("ExceptionManagerDefaultHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外: {0}
        ///---------------説明
        ///{1}
        ///---------------スタックトレース
        ///{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionManagerGeneralStacktrace {
            get {
                return ResourceManager.GetString("ExceptionManagerGeneralStacktrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///    の例外が発生したため、アプリケーションを終了します。以下の内容を作者へご連絡いただきますようお願いいたします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionManagerMessage {
            get {
                return ResourceManager.GetString("ExceptionManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---------------諸情報
        ///ソフトウェアバージョン: {0}
        ///Windows OS: {1} ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionManagerStacktraceEnd {
            get {
                return ResourceManager.GetString("ExceptionManagerStacktraceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワーク関係で問題が発生しました。ネットワーク状況をもう一度確認してみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionManagerWebExceptionHint {
            get {
                return ResourceManager.GetString("ExceptionManagerWebExceptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルがありません。
        ///ウィザードを利用して、簡単に設定することができます。
        ///
        ///[はい] でウィザードを、[いいえ] で基本設定ウィンドウを表示します。
        ///[キャンセル]でアプリケーションを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FirstRunDialog {
            get {
                return ResourceManager.GetString("FirstRunDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示されているログをすべて消去します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDeleteDialog {
            get {
                return ResourceManager.GetString("LogDeleteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 通の新着メッセージがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckCountBalloons {
            get {
                return ResourceManager.GetString("MailCheckCountBalloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 通の未読メッセージ -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckCountNotify {
            get {
                return ResourceManager.GetString("MailCheckCountNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　通信エラーが発生しました。: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckError {
            get {
                return ResourceManager.GetString("MailCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} つのアカウントでエラーが発生しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckErrorCount {
            get {
                return ResourceManager.GetString("MailCheckErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} つのアカウントでエラー発生。 -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckErrorCountNotify {
            get {
                return ResourceManager.GetString("MailCheckErrorCountNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} のメールをチェックしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailChecking {
            get {
                return ResourceManager.GetString("MailChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: {1} 通 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckMailCount {
            get {
                return ResourceManager.GetString("MailCheckMailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　未読メッセージはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckNoUnread {
            get {
                return ResourceManager.GetString("MailCheckNoUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　{0} 通の未読メッセージがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailCheckUnreadCount {
            get {
                return ResourceManager.GetString("MailCheckUnreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListInboxRestore {
            get {
                return ResourceManager.GetString("MessageListInboxRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信者:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListMailAuthor {
            get {
                return ResourceManager.GetString("MessageListMailAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   迷惑メールのチェック中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamChecking {
            get {
                return ResourceManager.GetString("MessageListSpamChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamError {
            get {
                return ResourceManager.GetString("MessageListSpamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックが完了しました。メール数: {0} 通。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamReceive {
            get {
                return ResourceManager.GetString("MessageListSpamReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックが完了しました。 全 {0} 通中  {1} 通表示。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListSpamReceiveOver {
            get {
                return ResourceManager.GetString("MessageListSpamReceiveOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信日時:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListToolTip {
            get {
                return ResourceManager.GetString("MessageListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListToolTipTime {
            get {
                return ResourceManager.GetString("MessageListToolTipTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再開(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyConnectMenuConnect {
            get {
                return ResourceManager.GetString("NotifyConnectMenuConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一時停止(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyConnectMenuDisconnect {
            get {
                return ResourceManager.GetString("NotifyConnectMenuDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   公式サイトを表示します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOfficialSiteDialog {
            get {
                return ResourceManager.GetString("NotifyOfficialSiteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中断しています - {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyPause {
            get {
                return ResourceManager.GetString("NotifyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてメールチェック(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupAllCheckMenu {
            get {
                return ResourceManager.GetString("PopupAllCheckMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント設定がひとつもありません。
        ///設定しないとメールチェックはおこなわれません。
        ///
        ///[OK]をクリックすると、基本設定ウィンドウを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunNoAccountDialog {
            get {
                return ResourceManager.GetString("RunNoAccountDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したアカウントを削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingAccountDelete {
            get {
                return ResourceManager.GetString("SettingAccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたフォントは使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFontNotAvailableRegular {
            get {
                return ResourceManager.GetString("SettingFontNotAvailableRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント名: {0}
        ///サイズ: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingMessageListFontInfo {
            get {
                return ResourceManager.GetString("SettingMessageListFontInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gekko は、Gmail の新着・未読メッセージがあるかチェックし通知して、その場で内容を見ることのできる常駐型ツールです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingMessageListPreviewDetail {
            get {
                return ResourceManager.GetString("SettingMessageListPreviewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信者: Gekko ユーザ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingMessageListPreviewSender {
            get {
                return ResourceManager.GetString("SettingMessageListPreviewSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gekko のメッセージ一覧プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingMessageListPreviewTitle {
            get {
                return ResourceManager.GetString("SettingMessageListPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント設定がひとつもありません。
        ///最低でも一つは設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingNoAccountError {
            get {
                return ResourceManager.GetString("SettingNoAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＭＳ ゴシック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsMessageListDefaultFont {
            get {
                return ResourceManager.GetString("SettingsMessageListDefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップに既に設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupAlreadyRegisted {
            get {
                return ResourceManager.GetString("SettingStartupAlreadyRegisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GmailChecker のスタートアップが登録されています。
        ///これを削除して、新たに登録し直しますか？
        ///
        ///[はい] で削除して作成、[いいえ] で残したまま作成、[キャンセル] で作成を中断します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupGmailChecker {
            get {
                return ResourceManager.GetString("SettingStartupGmailChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップに登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupRegested {
            get {
                return ResourceManager.GetString("SettingStartupRegested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップに登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupRegistConfirm {
            get {
                return ResourceManager.GetString("SettingStartupRegistConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップに登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupRegistError {
            get {
                return ResourceManager.GetString("SettingStartupRegistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップから削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupRestoreConfirm {
            get {
                return ResourceManager.GetString("SettingStartupRestoreConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップから削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupRestored {
            get {
                return ResourceManager.GetString("SettingStartupRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップにショートカットはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingStartupRestoreError {
            get {
                return ResourceManager.GetString("SettingStartupRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GmailChecker 2 - 月光 - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月光 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoftwareNameShort {
            get {
                return ResourceManager.GetString("SoftwareNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終チェック時間:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusLatestMailCheck {
            get {
                return ResourceManager.GetString("StatusLatestMailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョンアップ確認中にエラーが発生しました。
        ///{0}:
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionUpCheckError {
            get {
                return ResourceManager.GetString("VersionUpCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードが完了しました。
        ///{0} を終了して、アップデートをおこないますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionUpCompleted {
            get {
                return ResourceManager.GetString("VersionUpCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードの実行中にエラーが発生しました。
        ///{0}:
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionUpError {
            get {
                return ResourceManager.GetString("VersionUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このバージョンが最新です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionUpNotNewVersion {
            get {
                return ResourceManager.GetString("VersionUpNotNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデータ起動中にエラーが発生しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionUpRunException {
            get {
                return ResourceManager.GetString("VersionUpRunException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WizardCompleteButton {
            get {
                return ResourceManager.GetString("WizardCompleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着受信時に再生するサウンドを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WizardFifthTitle {
            get {
                return ResourceManager.GetString("WizardFifthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着を受信したときの通知方法を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WizardForthTitle {
            get {
                return ResourceManager.GetString("WizardForthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ(&amp;N) &gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WizardNextButton {
            get {
                return ResourceManager.GetString("WizardNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用するアカウントを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WizardSecondTitle {
            get {
                return ResourceManager.GetString("WizardSecondTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールチェックをする間隔を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WizardThirdTitle {
            get {
                return ResourceManager.GetString("WizardThirdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続を再開します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteLogConnectionResumed {
            get {
                return ResourceManager.GetString("WriteLogConnectionResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続を中断します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteLogConnectionStopped {
            get {
                return ResourceManager.GetString("WriteLogConnectionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続を再開しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteLogPowerResumed {
            get {
                return ResourceManager.GetString("WriteLogPowerResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows が中断されるため、接続を中断します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteLogPowerSuspention {
            get {
                return ResourceManager.GetString("WriteLogPowerSuspention", resourceCulture);
            }
        }
    }
}
